-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjURiLhpykATF1zYP
OnedWHzEeqZEdO93DwKrKXIhR3egCgYIKoZIzj0DAQehRANCAASHc4hmVHfmejSg
N+MKNYCKc0YMC9Evzhzw6NXRMoZanaFRHIvaq/KxLy1Wr9jNytf77vofmXLL/mBD
WcLemABo
-----END PRIVATE KEY-----