<?php

namespace App\CatalogModule\Models;

use App\DefaultPanel\Enum\SubscriptionsStatusEnum;
use App\DefaultPanel\Traits\Transactionable;
use App\Models\User;
use App\Notifications\DoctorSubscribedToPlanSuccessFullyNotification;
use App\UsersModule\Models\Provider;
use Cknow\Money\Money;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Money\Currency;
use Money\Money as BaseMoney;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;

class Subscription extends Model
{
    use HasFactory, LogsActivity, Transactionable;

    protected $guarded = ['id'];

    protected $casts = [
        'meta_data' => 'array',
        'features' => 'array',
        'plan_snapshot' => 'array',
        'status' => SubscriptionsStatusEnum::class,
    ];

    /**
     * Persisted when the subscription is created so plan / plan_price rows can be removed later.
     *
     * @return array{name: array<string, string>|mixed, commission_percent: ?string, plan_price: ?array{period: string, days_count: int}}
     */
    public static function buildPlanSnapshot(Plan $plan, ?PlanPrice $planPrice = null): array
    {
        return [
            'name' => $plan->getTranslations('name'),
            'commission_percent' => $plan->commission_percent !== null && $plan->commission_percent !== ''
                ? (string) $plan->commission_percent
                : null,
            'plan_price' => $planPrice ? [
                'period' => $planPrice->period,
                'days_count' => $planPrice->days_count,
            ] : null,
        ];
    }

    public function resolvedPlanName(?string $locale = null): string
    {
        $locale = $locale ?? app()->getLocale();
        $plan = $this->plan;
        if ($plan) {
            return $plan->displayName($locale);
        }

        $name = data_get($this->plan_snapshot, 'name');
        if (is_array($name)) {
            return (string) ($name[$locale] ?? $name['ar'] ?? $name['en'] ?? (string) (reset($name) ?: ''));
        }

        return '';
    }

    public function resolvedPeriodLabel(): string
    {
        if ($this->planPrice) {
            return $this->planPrice->period_label;
        }

        $period = data_get($this->plan_snapshot, 'plan_price.period');
        if (! is_string($period) || $period === '') {
            return '-';
        }

        return match ($period) {
            PlanPrice::PERIOD_MONTHLY => __('panel.enums.period_monthly'),
            PlanPrice::PERIOD_QUARTERLY => __('panel.enums.period_quarterly'),
            PlanPrice::PERIOD_YEARLY => __('panel.enums.period_yearly'),
            default => $period,
        };
    }

    /**
     * Same semantics as {@see Plan::$commission_percent} on the live plan row.
     */
    public function resolvedPlanCommissionPercent(): ?float
    {
        $plan = $this->plan;
        if ($plan && $plan->commission_percent !== null && $plan->commission_percent !== '') {
            return (float) $plan->commission_percent;
        }

        $v = data_get($this->plan_snapshot, 'commission_percent');
        if ($v === null || $v === '') {
            return null;
        }

        return (float) $v;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function ($subscription) {
            if ($subscription->status == SubscriptionsStatusEnum::PROCESSING) {
                $subscription->subscriber->notify(new DoctorSubscribedToPlanSuccessFullyNotification);
            }

        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->dontSubmitEmptyLogs()
            ->logOnly(['end_date', 'start_date'])
            ->logOnlyDirty();
    }

    public function scopeBelongsToAuthUser($builder)
    {
        $provider = provider();

        return $builder->where('user_id', $provider?->user_id);
    }

    public function scopeActive($builder)
    {
        return $builder->where('status', \App\DefaultPanel\Enum\SubscriptionsStatusEnum::PROCESSING)
            ->where('start_date', '<=', now())
            ->where('end_date', '>=', now());
    }

    public function planPrice()
    {
        return $this->belongsTo(PlanPrice::class);
    }

    public function price(): Attribute
    {
        return Attribute::make(
            get: function ($value) {
                if ($value === null || $value === '') {
                    return Money::parse(0);
                }

                // New subscriptions store minor units (Plan::createSubscriptionForProvider uses planPrice->price->getAmount()).
                // Money::parse(9900) treats that as major units → wrong display (e.g. 9,900.00 vs 99.00).
                // Legacy rows may store major decimal (e.g. 99) — use parse for small values.
                $amount = (int) round((float) $value);
                $currency = config('money.defaultCurrency', 'SAR');

                if ($amount >= 100) {
                    return Money::convert(new BaseMoney((string) $amount, new Currency($currency)));
                }

                return Money::parse($value);
            }
        );
    }

    public function subscriber(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function provider(): BelongsTo
    {
        return $this->belongsTo(Provider::class, 'user_id', 'user_id');
    }

    public function plan()
    {
        return $this->belongsTo(Plan::class);
    }

    public function isActive(): bool
    {
        return $this->status === \App\DefaultPanel\Enum\SubscriptionsStatusEnum::PROCESSING
            && $this->start_date <= now()
            && $this->end_date >= now();
    }

    public function isExpired(): bool
    {
        return $this->end_date < now();
    }
}
