<?php

namespace App\CatalogModule\Models;

use App\DefaultPanel\Enum\ReservationStatus;
use App\DefaultPanel\Enum\SubscriptionsStatusEnum;
use App\DefaultPanel\Traits\Transactionable;
use App\Models\User;
use App\Notifications\DoctorSubscribedToPlanSuccessFullyNotification;
use App\Notifications\ReservationCanceledFromPatientNotification;
use App\Notifications\ReservationScheduledNotification;
use App\Notifications\ReservationStatusChangedNotification;
use Cknow\Money\Money;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;


class Subscription extends Model {
    use HasFactory, Transactionable;

    protected $guarded = ['id'];
    protected $casts = [
        'meta_data' => 'array',
        'status' => SubscriptionsStatusEnum::class,

    ];

    protected static function boot() {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function ($subscription) {
            if (SubscriptionsStatusEnum::PROCESSING == $subscription->status) {
                $subscription->subscriber->notify(new DoctorSubscribedToPlanSuccessFullyNotification);
            }


        });
    }

    public function scopeBelongsToAuthUser($builder) {
        return $builder->where('user_id', doctor()?->user?->id);
    }

    public function price(): Attribute {

        return Attribute::make(
            get: fn($value) => Money::parse($value)
        );
    }


    public function subscriber(): BelongsTo {
        return $this->belongsTo(User::class, 'user_id');
    }


    public function plan() {
        return $this->belongsTo(Plan::class);
    }

}
