<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\UsersModule\Models\Provider;
use Str;
use App\CatalogModule\Models\Reservation;
use App\ContentModule\Models\BanksAccount;
use App\ContentModule\Models\City;
use App\ContentModule\Models\Point;
use App\DefaultPanel\Enum\UserStatus;
use App\Notifications\YourAccountActivatedNotification;
use App\Notifications\YourAccountInActivatedNotification;
use App\UsersModule\Models\DeviceToken;
use App\UsersModule\Models\User\Doctor;
use App\UsersModule\Models\User\Lab;
use App\UsersModule\Models\User\Patient;
use App\UsersModule\Models\VerificationCode;
use BezhanSalleh\FilamentShield\Traits\HasPanelShield;
use ChristianKuri\LaravelFavorite\Traits\Favoriteability;
use Filament\Models\Contracts\FilamentUser;
use Filament\Panel;
use Illuminate\Contracts\Translation\HasLocalePreference;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\Permission\Traits\HasRoles;
use Theamostafa\Wallet\Models\Transaction;
use Theamostafa\Wallet\Traits\HasWallet;
use App\UsersModule\Models\Users\Customer;
use App\UsersModule\Models\WithdrawalRequest;
use App\DefaultPanel\Enum\WalletWithdrawEnum;

class User extends Authenticatable implements HasMedia, FilamentUser, HasLocalePreference {
    use HasApiTokens, HasFactory, Notifiable;
    use HasRoles, InteractsWithMedia;
    use HasPanelShield, Favoriteability, HasWallet;


    protected $table = 'users';
    public $guard_name = 'web';


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'active',
        'api_token',
        'password',
        'phone_verified_at',
        'settings',
        'city_id',
        'dob',
        'gender',
        'data',
        'id_number'

    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];
    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        // Password is hashed in setPasswordAttribute (mutator runs before the "hashed" cast,
        // so the cast never applied and passwords were stored as plaintext — see mutator below).
        'settings' => 'array',
        'data' => 'array',
        'active' => UserStatus::class
    ];

    protected static function booted() {
        parent::booted(); // TODO: Change the autogenerated stub
        static::retrieved(function ($user) {
            // Only create wallet if user has an ID and wallet doesn't exist
            if ($user->id && !$user->wallet) {
                $user->wallet()->create([
                    'balance' => 0,
                    'name' => 'Default Wallet'
                ]);
            }
        });
    }

    public function getMorphClass(): string {
        return User::class;
    }

    public function provider(): HasOne {
        return $this->hasOne(Provider::class, "user_id");
    }

    public function supplier() {
        return $this->provider();
    }

    public function options() {
        return $this->hasOne(ProviderOption::class, "provider_id");
    }

    public function setPhoneAttribute($value): void {
        $this->attributes['phone'] = Str::replace(' ', '', $value);
    }

    public function setPasswordAttribute($value): void {
        if ($value === null || $value === '') {
            return;
        }
        // Already hashed (seeders, imports) — store as-is
        if (Hash::isHashed($value)) {
            $this->attributes['password'] = $value;

            return;
        }
        $this->attributes['password'] = Hash::make($value);
    }

    public function getStatusAttribute($value) {
        return $this->active->value;
    }

    public function toggleActive(): bool {
        if ($this->active->value) {

            $this->notify(new YourAccountInActivatedNotification());
            return $this->update(['active' => 0]);
        }
        $this->notify(new YourAccountActivatedNotification());
        return $this->update(['active' => 1]);
    }

    public function deviceTokens(): HasMany {
        return $this->hasMany(DeviceToken::class, "user_id");
    }

    public function notifications() {
        return $this->morphMany(Notification::class, 'notifiable')->latest();

    }

    public function isFirstTimeToLogin(): bool {
        return !$this->remember_token;
    }

    public function verified(): int {
        return !is_null($this->phone_verified_at);
    }

    public function bankAccount(): HasOne {
        return $this->hasOne(BanksAccount::class, "user_id");
    }

    public function verificationCodes(): HasMany {
        return $this->hasMany(VerificationCode::class, "user_id");
    }

    public function preferredLocale() {
        return 'ar';
    }

    public function addresses() {
        return $this->hasMany(AddressBook::class);
    }

    public function toCustomer(): HasOne {
        return $this->hasOne(Customer::class, 'id');
    }

    public function actAs($model) {
        return $this->hasOne($model, 'id')->first();
    }

    public function city() {
        return $this->belongsTo(City::class);
    }

    public function patient() {
        return $this->hasOne(Patient::class, 'id');
    }

    public function canAccessPanel(Panel $panel): bool {
        // Provider portal: registered providers awaiting first payment (pending) or active accounts.
        if ($panel->getId() === 'lab-panel' && $this->hasRole('provider')) {
            return in_array($this->active->value, [
                UserStatus::ACTIVE->value,
                UserStatus::PENDING->value,
            ], true);
        }

        return $this->active->value === UserStatus::ACTIVE->value;
    }

    public function reservations(): HasMany {
        return $this->hasMany(Reservation::class, 'user_id');
    }

    public function points() {
        return $this->hasMany(Point::class, 'user_id');
    }

    public function pointsExchanges(): HasMany {
        return $this->hasMany(PointsExchange::class, 'user_id');
    }

    public function getTotalPointsBalance() {
        return PointsExchange::where('user_id', $this->id)->where('expired_at', ">", now())
            ->where('used', 0)
            ->sum('reset_price');
    }

    public function getTotalPoints() {

        return $this
            ->points()
            ->where('transferred', false)
            ->sum('reset_points');
    }

    public function walletTransactions(): HasMany {
        return $this->hasMany(Transaction::class, 'wallet_id');
    }
    public function withdrawalRequests(): HasMany {
        return $this->hasMany(WithdrawalRequest::class, 'user_id');
    }

    public function hasPendingWithdrawalRequest(): bool {
        return $this->withdrawalRequests()
            ->whereIn('status', [WalletWithdrawEnum::PENDING, WalletWithdrawEnum::WAITING_TRANSFER])
            ->exists();
    }
}
